AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "db/**/*"

plugins:
  - rubocop-rspec
  - rubocop-sequel

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "services/**/*"
    - "app.rb"

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"
    - "services/**/*"
    - "app.rb"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Enabled: true
  Max: 10

RSpec/MultipleExpectations:
  Enabled: true
  Max: 3

RSpec/NestedGroups:
  Enabled: true
  Max: 4
